= Разработка драйверов в Linux
:doctype: article
:title-page:
:toc:
:toc-title: Оглавление
:toclevels: 3
:sectnums:
:icons: font
:source-highlighter: rouge
:figure-caption: Рисунок
:table-caption: Таблица
:example-caption: Пример
:listing-caption: Листинг
:pdf-theme: default-with-fallback-font
:author: Владислав Богданов
:email: vla-bogdano@ya.ru
:revdate: 2026-06-16

toc::[]


== Введение 

=== Необходимо 
* Виртуальная машина 
* Литература 
    ** Системное програмиирование Роберт Лав
    ** Understanding the Linux Kernel Daniel P. Bovet, Marco Cesati
    ** Разработка драйверов Linux Jonathan Corbet, A. Rubini

=== Основы
`System call` - обращение из кода програмы к системной функуции, к то му что называют системным именем system kernel symvol.

Первоначально в программировании под понятием _символ_ - понималось имя функции. 

То есть  system call - вызов функции из ядра (пример: Open(), close(), read(), write())

*Пользовательская программа* - то есть я могу только пользоваться *system call*. 

*Системная программа* - то есть я могу только пользоваться *system call* и создавать свои. 

Демон - пользовательский код, так как только вызывает системные вызовы. 

Написание драйверов создание новых системных вызовов. Для этого в Linux есть понятие модуля ядра (драйвер). 

Связь пользовательского по с устройством:
*device - IRQ - module - daemon - user*. 
Драйвером можно считать связку *IRQ - module - daemon*.

`module` - исходный код, текст программы,  который реализует логику передачи данных от оборудования (виртуального или реального) пользователю. Модуль должен котнтролировать процес подключения программы к устройству. 


*Виды устройств:*

* Символьные устройства (90%)

* Блочные устройства (диски), отличается от символьнгого. Другие права доступа и блочное устройство может сообщать системе информациб о геометрии диска(Цилиндры и тд). 

* Сетевые интерфейсы. Для реализации сетевого интерфейса нужна сетевая железка. 

* SCSI device

Взаимодействия с устройством происходит через файлы устройств. 

*Ключевые директории:*

. /dev

. /proc - служебная инфо о модуле

. /sys - можно задать параметры модулей 


*/proc/devices* - прочитав который можно увидеть мписок устройств в нашей системе. 

`Файлы устройств создает ?` 

=== Ососбенности написания кода для ядра

К примеру: 

. Нет операций с плавающей точкой (так как что бы использовать floating point operations она должна быть описана на уровне языка и компилироваться под систему, в самом ядре такого типа нет, а она пишется на пользовательском уровне)

. Используем числа с фиксированной точкой `fixed-point`

NOTE: Математика написана примерно в 70-х на fortrane. 

Помним 

IO

012

`Терминыы ввод вывод всегда меряются относиительно пользовательской программы. `
Поэтому 

stdin - 0 - read() -  пользовательсяка программа читает

stdout - 1 - write()  -  пользовательсяка программа пишет 

Когда мы работаем на уровне ядра, мы пишем ответную часть для пользовательского кода поэтому в ядре все кверху ногами.  

read() -  модулья ядра пишет

write() -  модулья ядра читает.


=== Инструментарий 

Команды для Debian образных систем 

. sudo
. su
. su ....  
. apt update 
. apt install gcc
. apt install build-essential 
. apt install libncurses6
. apt install libncurses-dev
. apt install libncursesw6
+
под 6 ядром 
+
. apt install flex 
. apt install bison 
. исходники ядра  apt install linux-source под свое ядро, версия ядра _uname -r_, появятся исходники в /usr/src в архиве. Для проверки перейти в директорию и запустить make menuconfig, 
запустится конфигуратор ядра.
+
----
cd /usr/src/linux-source-x.x.x/linux-source-x.x.x
sudo make menuconfig
----
+
. возможно apt upgrade 

 