= Как задействовать Module.symvers из ядра
:doctype: article
:title-page:
:toc:
:toc-title: Оглавление
:toclevels: 3
:sectnums:
:icons: font
:source-highlighter: rouge
:figure-caption: Рисунок
:table-caption: Таблица
:example-caption: Пример
:listing-caption: Листинг
:pdf-theme: default-with-fallback-font
:author: Владислав Богданов
:email: vla-bogdano@ya.ru
:revdate: {localdate}
:keywords: driver, module, kernel_symvol, Module.symvers

toc::[]


== Введение 

На сколько я понимаю, ядро мы дополняем модулями, в каждом модуле есть некие функции, некоторые из этих функций мы можем вызывать снаружи. 

Функцию к которой мы хотим предоставить доступ мы экспортируем:

* *EXPORT_SYMBOL(моя_функция);* — делает функцию доступной для любых модулей, даже проприетарных (закрытых).

* *EXPORT_SYMBOL_GPL(моя_функция);* — делает функцию доступной только для модулей, у которых в метаданных указана лицензия GPL (через MODULE_LICENSE("GPL");)

В результате в папке с получаемым драйвером мы получим файл _Module.symvers_. Это текстовый файл, в котором будет прописано:

. *CRC (Хеш)* — контрольная сумма символа.

. *Символ* — имя экспортируемой функции или переменной (например, printk, kmalloc).

. *Модуль* — где этот символ определен (например, vmlinux для самого ядра или snd для звуковой подсистемы).

. *Экспорт* — лицензионные ограничения (GPL, UNUSED и т.д.).

*Что это дает?*

Когда компилируем свой собственный (внешний) модуль, система сборки ядра (Kbuild) смотрит в Module.symvers основного ядра.

* Если наш модуль вызывает функцию kmalloc, компилятор проверяет Module.symvers, находит её там и понимает, как к ней обратиться.

* Самое главное: он сверяет CRC-хеш. Если разработчики ядра обновили ядро и изменили сигнатуру (аргументы) функции kmalloc, её CRC изменится. Наш модуль либо не соберется, либо не загрузится, выдав ошибку _disagrees about version of symbol_. Это спасает систему от страшных падений (Kernel Panic) из-за несовместимости версий!

== Как этим пользоваться на практике?

К примеру пишем два модуля:

. *math_lib.ko* - моя библиотека, в которой есть функция _int my_add(int a, int b)_.

. *client.ko* - модуль, который хочет использовать my_add. 

=== Как они «познакомятся» при сборке?

. Мы пишем _math_lib.c_, добавляем _EXPORT_SYMBOL(my_add);_ и собираем его. В папке с ним появляется файл _Module.symvers_, где есть хеш и адрес my_add.

. Мы пишем _client.c_, где объявляем функцию как внешнюю: _extern int my_add(int a, int b);_ и вызываем её.

Самое важное! Когда мы компилируем client.ko, система сборки (Kbuild) должна знать, где взять Module.symvers от math_lib. Если они лежат в разных папках, компилятор выдаст ошибку: my_add undefined!.

Чтобы это починить, при сборке client мы должны передать системе сборки путь к чужому Module.symvers. В Makefile это выглядит так:
[bash, code]
----
make -C /lib/modules/$(shell uname -r)/build M=$(PWD) KBUILD_EXTRA_SYMBOLS=/путь/к/math_lib/Module.symvers modules
----

=== Зависимость при загрузке

Когда скомпилируем оба модуля, то пробуем загрузить их через insmod:

Правильный порядок загрузки:

----
insmod math_lib.ko
insmod client.ko
----

NOTE: В реальной разработке используют modprobe, а не insmod. modprobe сам читает зависимости и загружает модули в правильном порядке)


== А теперь о ядре

В ядре уже есть написаные до нас функции которые мы можем использовать. 

=== . Где взять "Описание" функции? (Заголовочные файлы .h)

Чтобы компилятор (GCC) понял, как вызывать функцию (какие у нее аргументы, какой тип данных она возвращает), нужны заголовочные файлы ядра. Они лежат в директории с исходниками/заголовками (обычно _/usr/src/linux-headers-$(uname -r)/include/_).

*Пример:* Хочешь выделить память и вызываешь kmalloc.
В своем коде пишем: _#include <linux/slab.h>_.
Внутри этого .h файла написано описание: _void *kmalloc(size_t size, gfp_t flags);_.


=== Где взять "Разрешение"? (Файл Module.symvers)

А вот Module.symvers компилятору для описания не нужен. Он нужен линковщику и загрузчику модулей ядра.

Когда  скомпилируем свой модуль, загрузчик ядра (insmod или modprobe) посмотрит в системный Module.symvers. Он найдет там строчку вроде:

_0x1234abcd kmalloc vmlinux EXPORT_SYMBOL_

И поймет: "Ага, функция kmalloc разрешена к использованию, ее CRC-хеш совпадает с тем, что в моем ядре. Можно грузить модуль".

=== Что будет, если функции НЕТ в Module.symvers

И так мы нашли в исходниках ядра крутую внутреннюю функцию _super_secret_kernel_func()_.
Она описана в .h файле. Подключаем .h файл, пишем код, вызываем функцию.
Компилятор (GCC) отработает успешно! Код скомпилируется без ошибок, потому что описание есть.

Но когда попробуем загрузить модуль (_insmod my_module.ko_), ядро выдаст ошибку:
_my_module: Unknown symbol super_secret_kernel_func_
Потому что разработчики ядра не поставили макрос _EXPORT_SYMBOL_ для этой функции, и ее нет в Module.symvers. Ядро защищает свои внутренности!


=== Как на практике программисты ищут функции ядра?

Никто не читает Module.symvers глазами, чтобы найти нужную функцию (там сотни тысяч строк). 

*Программисты делают так:*

. *Читают исходники ядра*. Это главная документация.

. *Ищут макросы экспорта*. Если нужно понять, доступна ли функция внешним модулям, делают поиск по исходникам:
+
[bash]
----
grep -r "EXPORT_SYMBOL(имя_функции)" /usr/src/linux/
----
+
. *Читают KernelDoc*. Многие функции в ядре имеют подробные комментарии прямо в .c файлах, которые автоматически превращаются в документацию.