= Команды для работы с модулями ядра 
:doctype: article
:title-page:
:toc:
:toc-title: Оглавление
:toclevels: 3
:sectnums:
:icons: font
:source-highlighter: rouge
:figure-caption: Рисунок
:table-caption: Таблица
:example-caption: Пример
:listing-caption: Листинг
:pdf-theme: default-with-fallback-font
:author: Владислав Богданов
:email: vla-bogdano@ya.ru
:revdate: 2026-06-16
:keywords: kernel, driver, module, commands, udevadm, kmalloc, vmalloc, mmap 

toc::[]

== Полезные команды 

=== `insmod` 
Назначение: загрузка модуля по горячему 

=== `rmmod` 
Назначение: убрать из системы 

=== `lsmod` 
Назначение: список устройств в системе

=== `depmod` 
Назначение: устанавливает зависимости модулей в системе 
в папке _/lib/modules/7.0.0-22-generic_ расположены модули загружаемые системой, создаем там каталог _misc_ в него копируем свои модули, после запуска depmod он перестраивает зависимости и данные модули прекрасно запускаются с помощью modprobe. depmod нужно вызывать после того, как модули скопированы в системную папку модулей (например, lib/modules//misc).

=== `modprobe` 
Назначение: позволяет мягким образом работать с модулями. 
Загружает/Выгружает модули с зависимостями. 

----
//load module 
sudo modprobe hello
//delete module 
sudo modprobe -rf hello
----

=== `modinfo` 
Назначение: показывает информацию о модуле 

----
modinfo param_demo1.ko
filename:       /home/user/prj/linux/param_demo1/param_demo1.ko
author:         user
license:        GPL
srcversion:     23D76AE67C80B7BE8692A2F
depends:        
name:           param_demo1
retpoline:      Y
vermagic:       7.0.0-22-generic SMP preempt mod_unload modversions 
parm:           m_count:module_counter (int)
parm:           m_char:module_string (charp)
----

=== `cat /proc/devices` 
Назначение: можно посмотреть старшие номера устройств


=== `udevadm` 
Назначение: показывает полное дерево путей (DEVPATH).

----
# Смотрим физический порт (пример для ttyS0 или ttyAMA0)
udevadm info -q path -n /dev/ttyS0
# Вывод: /devices/platform/soc/serial@.../tty/ttyS0

# Смотрим виртуальный терминал
udevadm info -q path -n /dev/tty1
# Вывод: /devices/virtual/tty/tty1
----

=== `kmalloc`
Выделение памяти в ядре 

параметры (объем, флаги)

Флаги:

. GFP_KERNEL - означает что память выделяется в нижней памяти от имени  модуля, срабатывает от имени модуля и делает системный вызов выделения памяти. В случае недостатка памяти данный флаг разрешает наш процесс приостановить пока не наберется свободной памяти.То есть флаг блокирующий. Ядро при этом будет пытаться максимально быстро искать способы выделить память. В частности будет использоваться своп для пользовательских процессов. Флаг встречается в 90% программ. *Тонкий момент* флвг не всегда хорош. Не годится тогда когда процесс ядра не может спать. К примеру: обработчики прерываний, таймеры ядра.  

. GFP_ATOMIC - ядро выделяет память моментально или выдает сбой при невозможности. В ядре всегда есть некий запас страниц памяти для надежной работы.(ЛОГИКУ ЛУЧШЕ ПРИВЯЗЫВЫАТЬ К СТРАНИЦАМ). Просто так использовать данный флаг не рекомендуется. Вообще  получить сбой при выделении памяти очень сложно и сбой обычно означает либо аппаратные проблемы либо проблемы в логике программы. 

. GFP_USER - выделение памяти под страницы пространства пользователя, то есть память не под себя а под пользовательский процесс.  При этом память выделяется в нижней памяти. 

. GFP_HIGH_USER - - // - // - выделяет памчять в верхней памяти для пространства пользователя. 

Вспомогательные флаги используемые совместно с выше перечисленными: 

. GFP_NOIO - при выделении памяти запрещены любые операции ввода вывода. 

. GFP_NOFS - при выделении памяти запрещены любые операции с файловыми системами. 

и тд. 

Так же есть специальный флаг *__GFP_DMA* - заставляет выделить память в специальной DMA совместимой памяти. Она находится в диапазоне приверегированных адресов, там где переферийные устройства выполняют так называемый dma обращения. 

Ядро управляет памятью системы таким образом, что память выделяется так называемыми кусками  (slab) размером в страницу. Поэтому ядро и модули ядра могут выделять лишь некоторые заранее определенные объемы памяти с фиксированным количеством байт, то есть по сути кратно странице. 

linux/slab.h  - библиотека управления памятью. 

===  `vmalloc`
Выделяет непрерывную  с виртуальной точки зрения область памяти, но физически разнесённую соответственно можно не пользоваться vmalloc, а использовать alloc_page. vmalloc работает через alloc_page.  vmalloc - основной инструмент выделения памяти в linux.  *`В ядре использовать не рекомендуется`* он может быть фрагментирована, работает медленнее и из-за того что эта память в некоторых архитектурах может быть расположена строго на одном каком то участке памяти на нее может быть выделено места меньше  памяти чем на нижнюю, зависит от архитектуры. 
Может потребоваться для хранения большого количества информации. 

=== `get_zeroed_page(GFP_KERNEL)`

Возвращает указатель на нулевую (обнулённую) страницу памяти.
Удобно использовать для mmap, чтобы пользователю отдавать чистый буфер.


=== `mmap`
отображение памяти, позволяет выполнять отображение некого файла в оперативную память процесса ну или можно сказать  наоборот отображение памяти процесса в файл. То еть по сти мы свзываем однор с другим и меняя что то происходит изменение и во второй половине. К примеру в системе есть некий модуль устройства который  связывается с пользовательсокй программой к примеру через файл устройства в директории dev. И в этот файл с периодом в несоклько несколько миллисекунд идет обновление какой то информации. Можно открыть этот файл и читать эту информацию, это будет работа через процессы ввода вывода с учетом их ограничений и особенностей, но жет мы работаем с файлом из директории proc. если рассмотреть последовательность появления информации оборудование -> оперативка -> файл  то минуя файл и отображая оперативку как файл позволит упростить работу отображая пространство ядра в пространство пользователя.  




